[[tl]]
type = "day"
number = 0

[[tl]]
type = "place"
name = "Letisko Heathrow"
city = "Londýn"
time = 2021-03-10 15:05:00+00:00
picture = "https://thepointsguy.com/wp-content/uploads/2015/10/heathrow.png"

[[tl]]
type = "transport"
vehicle = "Lietadlom"
duration = "7 hodín 25 minút"

[[tl]]
type = "place"
name = "Letisko Hamad"
city = "Doha (Katar)"
time = 2021-03-10 22:30:00+03:00

[[tl]]
type = "transport"
vehicle = "Lietadlom"
duration = "10 hodín 25 minút"

[[tl]]
type = "day"
number = 1

[[tl]]
type = "place"
name = "Letisko Narita"
city = "Tokyo"
time = 2021-03-11 17:55:00+09:00

[[tl]]
type = "transport"
vehicle = "Autom"
duration = "1 hodina"

[[tl]]
type = "place"
name = "Hostel Sadou"
city = "Tokyo"
time = 2021-03-11 19:00:00+09:00

[[tl]]
type = "transport"
vehicle = "Pešo"
duration = "40 minút"

[[tl]]
type = "place"
name = "LaQua"
city = "Tokyo"
time = 2021-03-11 19:40:00+09:00

[[tl]]
type = "day"
number = 2

[[tl]]
type = "place"
name = "Ulice Tokya"
time = 2021-03-12 08:00:00+09:00

[[tl]]
type = "transport"
vehicle = "Autom"
duration = "15 minút"

[[tl]]
type = "place"
name = "Nezu múzeum"
time = 2021-03-12 10:00:00+09:00
duration = "2 hodiny"

[[tl]]
type = "transport"
vehicle = "Autom"
duration = "15 minút"

[[tl]]
type = "place"
name = "McDonald's"
time = 2021-03-12 12:30:00+09:00

[[tl]]
type = "transport"
vehicle = "Autom"
duration = "10 minút"

[[tl]]
type = "place"
name = "Maxell Aqua Park"
time = 2021-03-12 13:15:00+09:00
duration = "2 hodiny 45 minút"

[[tl]]
type = "transport"
vehicle = "Autom"
duration = "1 hodina 17 minút"
